/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class fun_inject_InjectorUtils */

#ifndef _Included_fun_inject_InjectorUtils
#define _Included_fun_inject_InjectorUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fun_inject_InjectorUtils
 * Method:    injector
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fun_inject_InjectorUtils_injector
  (JNIEnv *, jclass, jint,jstring);

#ifdef __cplusplus
}
#endif
#endif
